### PR TITLE
Don't report custom type constructor args used in comparisons

### LINKED ISSUE #25: False positive on `NoUnused.CustomTypeConstructorArg`
False positive on `NoUnused.CustomTypeConstructorArg` when the type is only use in equality comparisons.

**SSCCE (Short Self-Contained Correct Example)**
When running `npx elm-review --template jfmengels/elm-review-unused/example` on the following code:
```elm
module Main exposing (main)

import Html exposing (Html)


type Id
    = Id String


main : Html msg
main =
    Html.text <|
        if Id "A" == Id "A" then
            "OK"

        else
            "NOK"
```
I get:
```shell
-- ELM-REVIEW ERROR ------------------------------------------ src/Main.elm:7:10

NoUnused.CustomTypeConstructorArgs: Argument is never extracted and therefore
never used.

6| type Id
7|     = Id String
            ^^^^^^

This argument is never used. You should either use it somewhere, or remove it at
the location I pointed at.

I found 1 error in 1 file.
```
Even though I need the `String` parameter.

**Expected behavior**
No error reported.

**Additional context**
`elm-review` CLI version: 2.3.3
`"jfmengels/elm-review": "2.3.8"`
`"jfmengels/elm-review-unused": "1.1.4"`

### PR DESCRIPTION
**Pull request by jfmengels**
Fixes #25

When used in comparison, the arguments of a custom type constructor won't be reported.

```elm
-- Not reported
value == Foo 1
-- Still reported
value == fn (Foo 1)
```

@r-k-b This won't handle the case for `assoc-list` and I don't have a good idea to handle it. I added a warning in the rule's documentation though.

Please try it out:

```bash
elm-review --template jfmengels/elm-review-unused/preview#issue-25 --rules NoUnused.CustomTypeConstructorArgs
```

cc @lydell @jpagex

### CODE REVIEW

**Comment by lydell** [comment]
Cool!

I tried to simplify down my case:

```elm
module Simple exposing (update, view)

import Html exposing (Html)


type alias Model =
    { version : Version
    }


type Version
    = LatestVersion String
    | OutOfDateVersion


update : String -> Model -> Model
update justFetchedVersionString model =
    { model
        | version =
            if model.version == LatestVersion justFetchedVersionString then
                model.version

            else
                OutOfDateVersion
    }


view : Model -> Html msg
view model =
    case model.version of
        LatestVersion _ ->
            Html.text ""

        OutOfDateVersion ->
            Html.text "You need to update!"
```

This is the result:

```
❯ npx elm-review --template jfmengels/elm-review-unused/preview#issue-25 --rules NoUnused.CustomTypeConstructorArgs
npx: installed 125 in 8.083s
✔ Fetching template information
-- ELM-REVIEW ERROR --------------------------------------- src/Simple.elm:12:21

NoUnused.CustomTypeConstructorArgs: Argument is never extracted and therefore
never used.

11| type Version
12|     = LatestVersion String
                        ^^^^^^
13|     | OutOfDateVersion

This argument is never used. You should either use it somewhere, or remove it at
the location I pointed at.

I found 1 error in 1 file.
```

This shouldn’t be reported, should it? Or am I missing something 🤔

**Comment by jfmengels** [comment]
Yeah, it shouldn't. I made some mistakes in my tests and forgot to handle an essential thing. It should be fixed now though!

**Comment by lydell** [comment]
Thanks! Yes, now it seems to be fixed. Awesome! 🥇

**Comment by jfmengels** [comment]
Alright, released in 1.1.7 :)

**Pull request merged**
