### PR TITLE
Fix indirect nounused dependencies

### LINKED ISSUE #50: False positive on `NoUnused.Dependencies`
**Describe the bug**
`elm-review-unused` reports false positive `NoUnused.Dependencies`, seemingly when an indirect dependency has a module with the same name as a module in a direct dependency.

**SSCCE (Short Self-Contained Correct Example)**
1. Go to 'https://github.com/klaftertief/elm-review-unused-sscce'.
2. Clone the repo, install dependencies with `npm install`.
3. Run `npm run sscce`.
4. See that `f0i/iso8601` is falsely reported as unused. It is imported and used in `Main.elm`.

**Expected behavior**
`f0i/iso8601` should not be reported as unused.

**Additional context**
It seems to be that `elm-review-unused` relates the `Iso8601` module with the one from the indirect dependency `rtfeldman/elm-iso8601-date-strings`, which can't be used in user application code.

It's probably caused by turning a list of module and package names into a dictionary here. https://github.com/jfmengels/elm-review-unused/blob/9ea4ce690fd6adca787a23e96f672f84f122bd2b/src/NoUnused/Dependencies.elm#L70-L78
The dictionary uses module names as the key, so a module name can only be related to one package in the current implementation.

### PR DESCRIPTION
**Pull request by klaftertief**
Fixes #50

I was not really sure abut the tests, but this seems to work :-)

### CODE REVIEW

**Comment by jfmengels** [comment]
Awesome! Thank you!

This looks good to me. Have you been able to try this out on your project and confirm that it solves the issue?

**Comment by klaftertief** [comment]
Yes, I copied the rule with the fix as a custom rule, it's working for us.

**Comment by jfmengels** [comment]
Awesome! Thanks for working on this! 🙏

**Comment by jfmengels** [comment]
Released in v1.1.17!

**Pull request merged**
